Instale a extensão "REST Client" para executar as requisições abaixo:
###



GET http://localhost:3333/api/sistemasigla/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHVzZXIiOjEsImlhdCI6MTcyNDcxMjQyMywiZXhwIjoxNzI0NzE2MDIzfQ.P8dSfhieqnZUYolMANTV9V4jSVVSZD248T4P7IdY3qw
###

GET http://localhost:3333/api/sistemasigla/16
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHVzZXIiOjEsImlhdCI6MTcyNDcxMjQyMywiZXhwIjoxNzI0NzE2MDIzfQ.P8dSfhieqnZUYolMANTV9V4jSVVSZD248T4P7IdY3qw
###

GET http://localhost:3333/api/sistemasigla?idtiposistema=2&idsituacaosistema=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHVzZXIiOjEsImlhdCI6MTcyMDE0MDc2NywiZXhwIjoxNzIwMTQ0MzY3fQ.mkV78HcH0iv3DMlglBIbMVbYCiHEONJhbJopawo4Yno
###

POST http://localhost:3333/api/sistemasigla/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHVzZXIiOjEsImlhdCI6MTcyNDcxMjQyMywiZXhwIjoxNzI0NzE2MDIzfQ.P8dSfhieqnZUYolMANTV9V4jSVVSZD248T4P7IdY3qw

{
    "siglasistema": "TESTE2",
    "descricaosistema": "Informações sobre Teste1.",
    "idsistemapai": null,
    "idtiposistema": 2,
    "idarearesponsavel": 1,
    "idsituacaosistema": 1,l
    "dataproducao": null,
    "datainativacao": null,
    "obssistema": "",
    "sistemacritico": false,
    "gov_clientid": "",
    "gov_scopes": "",
    "gov_redirecturi": ""
}
###

PUT http://localhost:3333/api/sistemasigla/35
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHVzZXIiOjEsImlhdCI6MTcyMDE0MDc2NywiZXhwIjoxNzIwMTQ0MzY3fQ.mkV78HcH0iv3DMlglBIbMVbYCiHEONJhbJopawo4Yno

{
    "siglasistema": "TESTE10--",
    "descricaosistema": "Informações sobre Teste10.",
    "idsistemapai": null,
    "idtiposistema": 2,
    "idarearesponsavel": 1,
    "idsituacaosistema": 1,
    "dataproducao": "2024-06-26",
    "datainativacao": null,
    "obssistema": "",
    "sistemacritico": false,
    "gov_clientid": "",
    "gov_scopes": "",
    "gov_redirecturi": ""
}
###

DELETE http://localhost:3333/api/sistemasigla/35
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHVzZXIiOjEsImlhdCI6MTcyMDE0MDc2NywiZXhwIjoxNzIwMTQ0MzY3fQ.mkV78HcH0iv3DMlglBIbMVbYCiHEONJhbJopawo4Yno

