Instale a extensão "REST Client" para executar as requisições abaixo:
###



GET http://localhost:3333/api/versaotecnologia/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHVzZXIiOjEwLCJpYXQiOjE3MjY0OTkyMTksImV4cCI6MTcyNjUwMjgxOX0.N3oQDzgFZpdHAtTv2XhO4LyYfGh6g0UzFpUHMJHtUG4
###

GET http://localhost:3333/api/versaotecnologia/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHVzZXIiOjEwLCJpYXQiOjE3MjY0OTY5NTMsImV4cCI6MTcyNjUwMDU1M30.UWWcegJfKa6aBfbAW34gipjfvNKiU7yqqTssvN-m8LQ
###

POST http://localhost:3333/api/versaotecnologia/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHVzZXIiOjEwLCJpYXQiOjE3MjY0OTY5NTMsImV4cCI6MTcyNjUwMDU1M30.UWWcegJfKa6aBfbAW34gipjfvNKiU7yqqTssvN-m8LQ

{
    "idtecnologia": 1,
    "numeroversao": "1.0.0",
    "indversaoatual": true
}
###

PUT http://localhost:3333/api/versaotecnologia/104
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHVzZXIiOjEwLCJpYXQiOjE3MjY0OTY5NTMsImV4cCI6MTcyNjUwMDU1M30.UWWcegJfKa6aBfbAW34gipjfvNKiU7yqqTssvN-m8LQ

{
    "idtecnologia": 1,
    "numeroversao": "1.0.1",
    "indversaoatual": true
}
###

DELETE http://localhost:3333/api/versaotecnologia/104
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHVzZXIiOjEwLCJpYXQiOjE3MjY0OTY5NTMsImV4cCI6MTcyNjUwMDU1M30.UWWcegJfKa6aBfbAW34gipjfvNKiU7yqqTssvN-m8LQ

